### ISSUE TITLE
Bug-inducing typo in the cloud functions's docs

### ISSUE THREAD

**Issue by fpluis** [MoralisWeb3/issue-tracker#106]
At the [Calling via REST API](https://docs.moralis.io/moralis-server/cloud-code/cloud-functions#calling-via-rest-api) section, there is an example URL that reads:

```
https://1a2b3c4c5d6f.moralis.io:2053/server/functions/Hello?_ApplicationId=1a2b3c4c5d6f1a2b3c4c5d6f&name=CryptoChad
```

I copy-pasted this and replaced the server id and moralis app id with my own values, but I couldn't get it to work. The problem was in the "moralis.io" part of the domain, which should instead be "usemoralis.io". The fixed example would be:

```
https://1a2b3c4c5d6f.usemoralis.io:2053/server/functions/Hello?_ApplicationId=1a2b3c4c5d6f1a2b3c4c5d6f&name=CryptoChad
```

**Comment by filipmartinsson** [comment]
That URL is just an example URL, as it says in the docs. And as it says below that URL, you need to insert your full moralis server url, not just the server id. This is because different servers have different server URLs. Not every server has the usemoralis domain. 

The URL has the following structure:
1. Full Morlis server url.
2. /functions/.
3. Cloud Function Name.
4. ?_ApplicationId=yourMoralisAppId.
5. (optional) Cloud Function param key/value pairs: &param1=value&param2=value.
